### ISSUE TITLE
Webview Crash

### ISSUE THREAD

**Issue by Arkoprovo1996** [Fabb2303/ResurrectionRemix-M-Z00L#2]
After the update to Nougat, **Webview is crashing** ...
Please use the following:

[OpenGApps Webview Patches](http://opengapps.org/blog/post/2016/10/06/nougat-webview/)

*This is a change in Nougat .. this needs to be incorporated across all ROMs*

**Comment by Fabb2303** [comment]
https://github.com/ResurrectionRemix/android_frameworks_base/commit/c1c5c68fdbb10a961344d8255993d2b06da9bbd4
